[build]
  command = "npm run build"
  functions = "functions"
  publish = "public"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000
  autoLaunch = true

# Redirects and rewrites
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/study-content"
  to = "/.netlify/functions/study-content"
  status = 200

[[redirects]]
  from = "/chat"
  to = "/.netlify/functions/chat"
  status = 200

[[redirects]]
  from = "/data"
  to = "/.netlify/functions/data"
  status = 200

[[redirects]]
  from = "/flashcards"
  to = "/.netlify/functions/flashcards"
  status = 200

[[redirects]]
  from = "/quiz"
  to = "/.netlify/functions/quiz"
  status = 200 