[build]
  publish = "public"
  command = "npm run build"
  functions = "functions"

[dev]
  command = "npm run netlify:dev"
  port = 8888
  publish = "public"

# Redirects and rewrites
[[redirects]]
  from = "/api/chat"
  to = "/.netlify/functions/chat"
  status = 200

[[redirects]]
  from = "/api/flashcards"
  to = "/.netlify/functions/flashcards"
  status = 200

[[redirects]]
  from = "/api/quiz"
  to = "/.netlify/functions/quiz"
  status = 200

[[redirects]]
  from = "/api/topics"
  to = "/.netlify/functions/data?type=topics"
  status = 200

[[redirects]]
  from = "/api/videos"
  to = "/.netlify/functions/data?type=videos"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 